services:
  - type: web
    name: lost-found-api
    env: node
    buildCommand: npm install && npm rebuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000